EWB-1526 upgrade versions of graphql-kotlin and exposed library
zepben/evolve-super-pom pull request #24
Opened 2022-05-27 02:29 UTC by ZheWangJames

2022-05-27 02:29 UTC, ryanjcoleman commented
Task linked: [EWB-1526 Add graphql and jetbrains exposed dependencies to evolve-super-pom](https://app.clickup.com/t/6929263/EWB-1526)

2022-06-01 04:17 UTC, kgreav requested changes

2022-06-07 00:55 UTC, ZheWangJames commented on pom.xml
> +        <graphql-kotlin.version>4.0.0-alpha.15</graphql-kotlin.version>
okay.

2022-06-07 03:50 UTC, kgreav approved these changes

2022-06-07 03:50 UTC, merged